# site_blog_homepage:
#     pattern:  /
#     defaults: { _controller: SiteBlogBundle:Default:index }

# site_blog_list:
#     pattern:  /list
#     defaults: { _controller: SiteBlogBundle:Default:list }

# site_blog_show:
#     pattern:  /show/{id}
#     defaults: { _controller: SiteBlogBundle:Default:show,id:1 }
#     requirements:
#         id: \d+
