parameters:
#    site_blog.example.class: Site\BlogBundle\Example

services:
#    site_blog.example:
#        class: %site_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
